dist: trusty
language: generic

env:
  global:
    - ENCRYPTION_LABEL="f5b0eb183bc9"
    - DEPLOY_USER="annevankesteren"

script:
  - curl --remote-name --fail https://resources.whatwg.org/build/deploy.sh && bash ./deploy.sh

notifications:
  email:
    on_success: never
    on_failure: always
